### ISSUE TITLE
ng-stack/form (2.2.3) Does not compile when target is es5

### ISSUE THREAD

**Issue by chandermani** [KostyaTretyak/ng-stack#80]
I have a webpack based Angular setup and the first time compilation for this module fails with error

```
Compiling @ng-stack/forms : module as esm5
Error: Error on worker #1: Error: getInternalNameOfClass() called on a non-ES5 class: expected FormBuilder to have an inner class declaration
    at Esm5ReflectionHost.getInternalNameOfClass (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\host\esm5_host.js:88:23)
    at DelegatingReflectionHost.getInternalNameOfClass (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\host\delegating_host.js:89:34)
    at extractInjectableMetadata (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:125:69)
    at InjectableDecoratorHandler.analyze (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\annotations\src\injectable.js:66:24)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:345:40)
    at analyze (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:297:58)
    at _loop_1 (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:319:21)
    at NgccTraitCompiler.TraitCompiler.analyzeClass (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\src\ngtsc\transform\src\compilation.js:325:35)
    at NgccTraitCompiler.analyzeFile (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\analysis\ngcc_trait_compiler.js:47:26)
    at DecorationAnalyzer.analyzeProgram (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\analysis\decoration_analyzer.js:134:39)
    at ClusterMaster.onWorkerMessage (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:194:27)
    at F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:54:95
    at ClusterMaster.<anonymous> (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:292:57)
    at step (F:\testapp\BOD\testapp.web\ClientApp\node_modules\tslib\tslib.js:141:27)
    at Object.next (F:\testapp\BOD\testapp.web\ClientApp\node_modules\tslib\tslib.js:122:57)
    at F:\testapp\BOD\testapp.web\ClientApp\node_modules\tslib\tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (F:\testapp\BOD\testapp.web\ClientApp\node_modules\tslib\tslib.js:111:16)
    at EventEmitter.<anonymous> (F:\testapp\BOD\testapp.web\ClientApp\node_modules\@angular\compiler-cli\ngcc\src\execution\cluster\master.js:286:32)
    at EventEmitter.emit (events.js:314:20)
F:\testapp\BOD\testapp.Web\ClientApp\node_modules\webpack-cli\bin\cli.js:281
                                throw err;
```

Here are my `tsconfig.json` settings

```
{
  "compileOnSave": true,
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "baseUrl": "./src",
    "lib": [ "ES6","DOM" ],
    "module": "commonjs",
    "moduleResolution": "node",
    "downlevelIteration": true,
    "noImplicitAny": false,
    "importHelpers": true,
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [ "./node_modules/@types" ],
    "paths":{
      "test/*": ["../test/*"],
      "core/*":["./_core/*"],
      "shared/*":["./_shared/*"],
    }
  },
  "include": [ "./src/**/*.ts", "./map/**/*.ts" ],
  "exclude": [ "./node_modules/**/*"],
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true
  }
}
```

**Comment by KostyaTretyak** [comment]
What version of Angular do you have?

**Comment by chandermani** [comment]
I am using Angular `9.1.6`. I was able to make version `2.1.1` work for me!

**Comment by KostyaTretyak** [comment]
@chandermani, I am tested Angular v9.1.6 on new project with your `tsconfig.json` and `@ng-stack/forms` v2.2.3. No issue with command `ng serve` or `ng build`.

**Comment by KostyaTretyak** [comment]
Oh, now I see

**Comment by KostyaTretyak** [comment]
Strange behavior of Angular CLI: when I change target to `es2015`, run `ng serve`, and then change target to `es5`, commands `ng serve` and `ng build` works as expected. I think this issue Angular CLI related.

**Comment by KostyaTretyak** [comment]
Also, you can try:

```bash
git clone git@github.com:KostyaTretyak/ng-stack.git
cd ng-stack
```

Change target in `projects/forms/tsconfig.lib.prod.json` to `es6`, and then

```bash
ng build forms --prod
cd dist/forms
npm pack
```

The last command will create an archive file `ng-stack-forms-2.2.3.tgz` that you can specify in your project to install:
```bash
cd to/your/project
npm install path/to/dist/forms/ng-stack-forms-2.2.3.tgz
```

**Comment by chandermani** [comment]
> 
> 
> Strange behavior of Angular CLI: when I change target to `es2015`, run `ng serve`, and then change target to `es5`, commands `ng serve` and `ng build` works as expected. I think this issue Angular CLI related.

@KostyaTretyak I am not using Angular CLI at all, instead I have a customer webpack setup. 

Will try your last suggestion
